### PR TITLE
Early changes to class 3

### PR DESCRIPTION
**Pull request by StabbyCutyou**
Still a WIP @amandamunoz

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
Added some more updates, would like to get your feedback.

**Comment by StabbyCutyou** [comment]
I'm gonna tweak the whole "English Number" thing, i feel like it's probably asking a bit much of people given the last class. I'm gonna come up with a simpler idea.

**Comment by amandamunoz** [comment]
lookin good to me

**Comment by StabbyCutyou** [comment]
Added some more changes - i dropped a slide or two, as i felt i'd rather allow for a little more time on some of the stuff that's here, and that also I felt might just lose people. I changed the "english number" method to a basic calculator method, then the homework building off of it is to make that into a calculator class, with methods for the 4 major operations. Simple, but i figured it's something people can reason about easily in their heads, so maybe not so intimidating. Plus it builds on almost everything we've already done.

**Comment by StabbyCutyou** [comment]
Hey Amanda,

If you get a few minutes, peep at some of the later changes I made. It's not all that different, but a few more things trimmed and hopefully a better homework assignment that builds off of the new class assignment.

I need to link to the homework slides, but i also still have them in the main presentation too, but i wanted to get this merged in so i could verify the link on your .io page first before putting it into the final set.

Thanks again! Looking forward to tonight. Hopefully they don't boo me off stage.

**Pull request merged**
